In [1]:
import numpy as np
import pandas as pd

<h4>Step1. data preprocessing</h4>

In [2]:
#load the dataset ratings
original_ratings_df=pd.read_csv("E:/MyCourses/CSC478ProgrammingMachineLearning/finalProject/moviedata/ratings.csv",sep=',')
original_ratings_df

userId  movieId  rating   timestamp
0            1        1     4.0   964982703
1            1        3     4.0   964981247
2            1        6     4.0   964982224
3            1       47     5.0   964983815
4            1       50     5.0   964982931
...        ...      ...     ...         ...
100831     610   166534     4.0  1493848402
100832     610   168248     5.0  1493850091
100833     610   168250     5.0  1494273047
100834     610   168252     5.0  1493846352
100835     610   170875     3.0  1493846415

[100836 rows x 4 columns]

In [3]:
#load the dataset movies
movies_df=pd.read_csv("E:/MyCourses/CSC478ProgrammingMachineLearning/finalProject/moviedata/movies.csv",sep=',',index_col=0)
movies_df

title  \
movieId                                              
1                                 Toy Story (1995)   
2                                   Jumanji (1995)   
3                          Grumpier Old Men (1995)   
4                         Waiting to Exhale (1995)   
5               Father of the Bride Part II (1995)   
...                                            ...   
193581   Black Butler: Book of the Atlantic (2017)   
193583                No Game No Life: Zero (2017)   
193585                                Flint (2017)   
193587         Bungo Stray Dogs: Dead Apple (2018)   
193609         Andrew Dice Clay: Dice Rules (1991)   

                                              genres  
movieId                                               
1        Adventure|Animation|Children|Comedy|Fantasy  
2                         Adventure|Children|Fantasy  
3                                     Comedy|Romance  
4                               Comedy|Drama|Romance  
5                                             Comedy  
...                                              ...  
193581               Action|Animation|Comedy|Fantasy  
193583                      Animation|Comedy|Fantasy  
193585                                         Drama  
193587                              Action|Animation  
193609                                        Comedy  

[9742 rows x 2 columns]

In [4]:
user_num=original_ratings_df.userId.nunique()
print('user_num: ',user_num)
movie_num=original_ratings_df.movieId.nunique()
print('movie_num: ',movie_num)

user_num:  610
movie_num:  9724


In [5]:
user_header=original_ratings_df.userId.unique()
movie_index=original_ratings_df.movieId.unique()

In [6]:
#recreate a ratings dataset, let the header be userId and index be movieId
ratings_data=np.zeros((movie_num,user_num))
ratings_data

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [7]:
ratings_df=pd.DataFrame(data=ratings_data,index=movie_index,columns=user_header)
ratings_df

1    2    3    4    5    6    7    8    9    10   ...  601  602  603  \
1       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
3       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
6       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
47      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
50      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
...     ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
160341  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
160527  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
160836  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
163937  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
163981  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   

        604  605  606  607  608  609  610  
1       0.0  0.0  0.0  0.0  0.0  0.0  0.0  
3       0.0  0.0  0.0  0.0  0.0  0.0  0.0  
6       0.0  0.0  0.0  0.0  0.0  0.0  0.0  
47      0.0  0.0  0.0  0.0  0.0  0.0  0.0  
50      0.0  0.0  0.0  0.0  0.0  0.0  0.0  
...     ...  ...  ...  ...  ...  ...  ...  
160341  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
160527  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
160836  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
163937  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
163981  0.0  0.0  0.0  0.0  0.0  0.0  0.0  

[9724 rows x 610 columns]

In [8]:
#fill the original data to the new dataframe, 0.0 means the user didn't rate the movie
for index,row in original_ratings_df.iterrows():
    r=row['movieId']
    c=row['userId']
    ratings_df.loc[r,c]=row['rating']
ratings_df

1    2    3    4    5    6    7    8    9    10   ...  601  602  603  \
1       4.0  0.0  0.0  0.0  4.0  0.0  4.5  0.0  0.0  0.0  ...  4.0  0.0  4.0   
3       4.0  0.0  0.0  0.0  0.0  5.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
6       4.0  0.0  0.0  0.0  0.0  4.0  0.0  0.0  0.0  0.0  ...  0.0  3.0  4.0   
47      5.0  0.0  0.0  2.0  0.0  4.0  0.0  4.0  0.0  0.0  ...  4.0  5.0  0.0   
50      5.0  0.0  0.0  0.0  4.0  1.0  4.5  5.0  0.0  0.0  ...  5.0  5.0  0.0   
...     ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
160341  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
160527  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
160836  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
163937  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
163981  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   

        604  605  606  607  608  609  610  
1       3.0  4.0  2.5  4.0  2.5  3.0  5.0  
3       0.0  0.0  0.0  0.0  2.0  0.0  0.0  
6       3.0  0.0  0.0  0.0  0.0  0.0  5.0  
47      0.0  0.0  3.0  0.0  4.5  0.0  5.0  
50      0.0  0.0  4.5  0.0  4.5  0.0  4.0  
...     ...  ...  ...  ...  ...  ...  ...  
160341  0.0  0.0  0.0  0.0  0.0  0.0  2.5  
160527  0.0  0.0  0.0  0.0  0.0  0.0  4.5  
160836  0.0  0.0  0.0  0.0  0.0  0.0  3.0  
163937  0.0  0.0  0.0  0.0  0.0  0.0  3.5  
163981  0.0  0.0  0.0  0.0  0.0  0.0  3.5  

[9724 rows x 610 columns]

In [9]:
ratings_arr=np.array(ratings_df)
ratings_arr

array([[4. , 0. , 0. , ..., 2.5, 3. , 5. ],
       [4. , 0. , 0. , ..., 2. , 0. , 0. ],
       [4. , 0. , 0. , ..., 0. , 0. , 5. ],
       ...,
       [0. , 0. , 0. , ..., 0. , 0. , 3. ],
       [0. , 0. , 0. , ..., 0. , 0. , 3.5],
       [0. , 0. , 0. , ..., 0. , 0. , 3.5]])

In [10]:
#did_ratings_arr is used to decide whether a certain movie is rated by a certain user
did_ratings_arr=(ratings_arr!=0)*1
did_ratings_arr

array([[1, 0, 0, ..., 1, 1, 1],
       [1, 0, 0, ..., 1, 0, 0],
       [1, 0, 0, ..., 0, 0, 1],
       ...,
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 1]])

In [11]:
ratings_mean = np.true_divide(ratings_arr.sum(1),(ratings_arr!=0).sum(1))
ratings_mean

array([3.92093023, 3.25961538, 3.94607843, ..., 3.        , 3.5       ,
       3.5       ])

In [12]:
ratings_mean_df=pd.DataFrame(data=ratings_mean,index=movie_index)
ratings_mean_df

0
1       3.920930
3       3.259615
6       3.946078
47      3.975369
50      4.237745
...          ...
160341  2.500000
160527  4.500000
160836  3.000000
163937  3.500000
163981  3.500000

[9724 rows x 1 columns]

<h4>Step2. generate movie features and user preferences</h4>

In [13]:
#choose a certain movie features count
movie_feature_num=5

In [14]:
#randomly generate movie features and user preferences
#then we will use gradient descent to approach the optimal value
movie_feature_arr=np.random.randn(movie_num,movie_feature_num)
user_prefs=np.random.randn(user_num,movie_feature_num)

In [15]:
movie_feature_arr

array([[ 0.08673071, -1.45623762, -0.71690811,  0.56940428,  0.28418335],
       [-0.68504023, -0.01171159,  0.75376497,  0.10164719, -0.9297926 ],
       [-1.43187839,  2.16844113,  0.72058785,  1.39500807,  0.08944791],
       ...,
       [ 0.63006556,  0.7745833 ,  0.08989993,  0.17261859, -1.61911515],
       [ 0.64037755, -0.56444658,  0.59562773, -0.70006365, -1.45717613],
       [-0.64378512,  0.49655951,  0.6571958 , -0.38178866,  0.72763484]])

In [16]:
#this method is from class example.
def matrix_factorization(R, P, Q, K, steps=1000, alpha=0.002, beta=0.002):
    ### R = The user x item rating matrix (m x n)
    ### P = Initial user-preference matrix (m x k)
    ### Q = Initial movie-features matrix (n x k)
    ### K = The number of features
    ### steps = The number of epochs in gradient descent
    ### alpha = The learning rate for gradient descent
    ### beta = The regularization coefficient
    Q = Q.T
    for step in range(steps):
        for i in range(len(R)):
            for j in range(len(R[i])):
                if R[i][j] > 0:
                    eij = R[i][j] - np.dot(P[i,:],Q[:,j])
                    for k in range(K):
                        ### update P and Q based on the partial derivatives of the loss function
                        P[i][k] = P[i][k] + alpha * (2 * eij * Q[k][j] - beta * P[i][k])
                        Q[k][j] = Q[k][j] + alpha * (2 * eij * P[i][k] - beta * Q[k][j])
        e = 0
        for i in range(len(R)):
            for j in range(len(R[i])):
                if R[i][j] > 0:
                    e = e + pow(R[i][j] - np.dot(P[i,:],Q[:,j]), 2)
                    for k in range(K):
                        e = e + (beta/2) * ( pow(P[i][k],2) + pow(Q[k][j],2) )
        e=e/np.count_nonzero(R)
        if e < 0.1:
            break
        print("Step %d of %d; Error: %0.5f; Time: %0.2f" %(step+1, steps, e, time()))
    return P, Q.T

In [17]:
from time import time
t0 = time()
result = matrix_factorization(ratings_data,movie_feature_arr,user_prefs,movie_feature_num)
print("done in %0.3fs." % (time() - t0))

Step 1 of 1000; Error: 13.39324; Time: 1591635454.54
Step 2 of 1000; Error: 9.97003; Time: 1591635462.57
Step 3 of 1000; Error: 6.25768; Time: 1591635470.59
Step 4 of 1000; Error: 4.57641; Time: 1591635478.64
Step 5 of 1000; Error: 3.67174; Time: 1591635486.74
Step 6 of 1000; Error: 3.09695; Time: 1591635494.80
Step 7 of 1000; Error: 2.69273; Time: 1591635503.01
Step 8 of 1000; Error: 2.38989; Time: 1591635511.23
Step 9 of 1000; Error: 2.15368; Time: 1591635519.27
Step 10 of 1000; Error: 1.96441; Time: 1591635527.40
Step 11 of 1000; Error: 1.80978; Time: 1591635535.49
Step 12 of 1000; Error: 1.68161; Time: 1591635543.64
Step 13 of 1000; Error: 1.57409; Time: 1591635551.72
Step 14 of 1000; Error: 1.48299; Time: 1591635559.80
Step 15 of 1000; Error: 1.40511; Time: 1591635568.10
Step 16 of 1000; Error: 1.33796; Time: 1591635576.57
Step 17 of 1000; Error: 1.27962; Time: 1591635584.82
Step 18 of 1000; Error: 1.22853; Time: 1591635593.24
Step 19 of 1000; Error: 1.18347; Time: 1591635604.62
S

In [18]:
from time import time
t0 = time()
result = matrix_factorization(ratings_data,result[0],result[1],movie_feature_num,steps=10,alpha=0.0002)
print("done in %0.3fs." % (time() - t0))

Step 1 of 10; Error: 0.41710; Time: 1591644332.87
Step 2 of 10; Error: 0.41590; Time: 1591644341.53
Step 3 of 10; Error: 0.41533; Time: 1591644349.95
Step 4 of 10; Error: 0.41501; Time: 1591644358.47
Step 5 of 10; Error: 0.41481; Time: 1591644367.25
Step 6 of 10; Error: 0.41467; Time: 1591644375.91
Step 7 of 10; Error: 0.41457; Time: 1591644384.31
Step 8 of 10; Error: 0.41449; Time: 1591644392.73
Step 9 of 10; Error: 0.41443; Time: 1591644400.94
Step 10 of 10; Error: 0.41438; Time: 1591644409.57
done in 85.026s.


In [19]:
optimal_movie_features=result[0]
optimal_user_prefs=result[1]

<h4>Step3. Now let's make predictions with the movie_features and user_prefs!</h4>

In [20]:
all_predictions = optimal_movie_features.dot(optimal_user_prefs.T)
all_predictions

array([[ 4.57632727,  3.29874172, -0.57372615, ...,  3.42333591,
         3.58646724,  4.03163058],
       [ 4.22504574,  3.11283782,  0.67355939, ...,  3.2436625 ,
         3.02610114,  3.31005417],
       [ 4.65344092,  3.98655178,  1.98884623, ...,  3.72081556,
         3.46242836,  4.20764924],
       ...,
       [ 3.10468959,  3.4967971 ,  2.82862443, ...,  2.97781001,
         2.71591515,  3.03785131],
       [ 2.94589241,  2.51770235,  1.0274263 , ...,  2.45567164,
         2.30338111,  3.52117226],
       [ 4.32234205,  3.29173442, -0.19344854, ...,  3.00322746,
         3.33234526,  3.52786166]])

In [21]:
predicted_ratings_df=pd.DataFrame(data=all_predictions,index=movie_index,columns=user_header)
predicted_ratings_df

1         2         3         4         5         6         7    \
1       4.576327  3.298742 -0.573726  3.065280  4.041270  4.509608  4.229836   
3       4.225046  3.112838  0.673559  2.613146  2.608790  3.411601  2.744982   
6       4.653441  3.986552  1.988846  3.462135  3.382861  4.028064  3.826765   
47      4.927991  3.819982  1.221983  4.068381  4.104366  3.865309  3.721193   
50      4.945753  3.865461  1.215865  4.017897  4.229672  3.969369  4.019960   
...          ...       ...       ...       ...       ...       ...       ...   
160341  2.762888  0.544372 -5.385754  3.684406  5.598865  2.770244  2.535429   
160527  6.169331  7.171250  7.824729  6.515697  3.464823  5.700220  3.897971   
160836  3.104690  3.496797  2.828624  0.833757  1.200934  3.895406  4.083018   
163937  2.945892  2.517702  1.027426  2.174512  2.890368  2.657071  3.521530   
163981  4.322342  3.291734 -0.193449  4.368915  4.547686  4.179617  3.406296   

             8         9         10   ...       601       602       603  \
1       4.008992  3.531854  4.177835  ...  4.436352  4.116405  3.285635   
3       3.438210  3.158868  3.672580  ...  3.736633  2.991953  2.795275   
6       3.320106  4.254994  2.120419  ...  4.256372  3.920565  3.949598   
47      4.282163  4.198218  1.563340  ...  4.436353  3.878701  4.076148   
50      4.120125  4.483305  1.254829  ...  4.537716  4.123298  4.432154   
...          ...       ...       ...  ...       ...       ...       ...   
160341  6.055276 -0.038912  3.063218  ...  2.784209  2.177704  0.237578   
160527  4.351633  4.319437  3.580575  ...  4.954509  4.158238  2.714842   
160836 -0.079608  4.231100  2.800576  ...  3.275190  3.871782  3.761792   
163937  1.614040  3.894627 -0.887109  ...  3.024667  3.383577  4.160300   
163981  5.064547  2.196775  3.760197  ...  3.920292  3.303415  1.742424   

             604       605       606       607       608       609       610  
1       4.253752  3.608613  3.923789  3.528806  3.423336  3.586467  4.031631  
3       3.210839  3.048465  3.288001  3.389825  3.243662  3.026101  3.310054  
6       3.907068  3.545308  3.950980  3.919248  3.720816  3.462428  4.207649  
47      3.968787  3.479808  4.219721  4.160298  3.762983  3.546329  4.515509  
50      4.052817  3.494043  4.407129  4.057007  3.813079  3.603213  4.699527  
...          ...       ...       ...       ...       ...       ...       ...  
160341  3.254233  2.037353  2.203467  2.503317  1.197789  2.208790  2.500155  
160527  5.670838  5.826102  3.527121  7.502713  5.124145  4.587500  4.570509  
160836  3.129501  2.963648  3.044576  2.066321  2.977810  2.715915  3.037851  
163937  2.644702  2.065512  3.344752  1.965456  2.455672  2.303381  3.521172  
163981  4.293725  3.648270  3.066852  4.324047  3.003227  3.332345  3.527862  

[9724 rows x 610 columns]

In [22]:
user1_rating=predicted_ratings_df.loc[:,1]
user1_rating.sort_values(ascending=False)

26761     12.014603
83969     11.896987
51167     11.551188
144222    11.279761
35807     10.925905
            ...    
1519      -3.059624
91414     -3.366135
136850    -4.068481
82684     -4.858991
5764      -5.199694
Name: 1, Length: 9724, dtype: float64

<h4>Step4. Print Mean Absolute Error for each user and overall mean absolute</h4>

In [23]:
#evaluate model precision, print the Mean Absolute Error
def print_MAE(R, A):
    totCount = 0
    totError = 0
    M=len(R)
    N=len(R[0])
    for u in range(N):
        err_u = 0
        rateCount_u = 0
        for j in range(M):
            if (ratings_data[j,u] > 0): ### Only use known ratings computing error
                rateCount_u += 1
                err_u += abs(all_predictions[j][u]- ratings_data[j,u])
        print("Mean Absolute Error for User %d = %0.5f" %(u+1, err_u/rateCount_u))
        totCount += rateCount_u
        totError += err_u
    print
    print("Overall Mean Absolute Error = %0.5f" %(totError/totCount))

In [24]:
print_MAE(ratings_data, all_predictions)

Mean Absolute Error for User 1 = 0.50124
Mean Absolute Error for User 2 = 0.47996
Mean Absolute Error for User 3 = 0.18896
Mean Absolute Error for User 4 = 0.65659
Mean Absolute Error for User 5 = 0.60821
Mean Absolute Error for User 6 = 0.45149
Mean Absolute Error for User 7 = 0.65619
Mean Absolute Error for User 8 = 0.63872
Mean Absolute Error for User 9 = 0.39392
Mean Absolute Error for User 10 = 0.38640
Mean Absolute Error for User 11 = 0.47775
Mean Absolute Error for User 12 = 0.49727
Mean Absolute Error for User 13 = 0.43224
Mean Absolute Error for User 14 = 0.53480
Mean Absolute Error for User 15 = 0.59225
Mean Absolute Error for User 16 = 0.39720
Mean Absolute Error for User 17 = 0.39172
Mean Absolute Error for User 18 = 0.33318
Mean Absolute Error for User 19 = 0.53405
Mean Absolute Error for User 20 = 0.42748
Mean Absolute Error for User 21 = 0.44092
Mean Absolute Error for User 22 = 0.50396
Mean Absolute Error for User 23 = 0.42122
Mean Absolute Error for User 24 = 0.33698
M

<h4>Step5.show recommended movie list for a certain user</h4>

In [27]:
def get_recommended_top_unrated(predicted_df, did_rating_df, ratings_mean_df, movies_df, userId, num):
    list=[]
    count=0
    user_rating = predicted_ratings_df.loc[:,userId]
    user_rating_sort=user_rating.sort_values(ascending=False)
    for index, value in user_rating_sort.items():
        if(did_rating_df.loc[index,userId]==0):
            list.append((index,value,ratings_mean_df.loc[index,0]))
            print("movie name: ",movies_df.loc[index,"title"],
                  " pred rating: %.3f "%value, " mean rating: %.3f "%ratings_mean_df.loc[index,0])
            count+=1
            if(count==num):
                break
    return list

In [28]:
did_rating_df=pd.DataFrame(data=did_ratings_arr,index=movie_index,columns=user_header)

In [30]:
#As you can see, predicted ratings can be higher than 5, which means it's predicted that the user
# may give a very high score. 
list=get_recommended_top_unrated(predicted_ratings_df,did_rating_df,ratings_mean_df,movies_df,2,10)

movie name:  Prime Suspect 2 (1992)  pred rating: 9.910   mean rating: 3.000 
movie name:  Beer League (2006)  pred rating: 8.922   mean rating: 4.000 
movie name:  There Will Come a Day (2013)  pred rating: 8.860   mean rating: 3.500 
movie name:  Times of Harvey Milk, The (1984)  pred rating: 8.811   mean rating: 4.500 
movie name:  Tyler Perry's I Can Do Bad All by Myself (2009)  pred rating: 8.789   mean rating: 5.000 
movie name:  Act of Killing, The (2012)  pred rating: 8.678   mean rating: 5.000 
movie name:  Son of the Bride (Hijo de la novia, El) (2001)  pred rating: 8.640   mean rating: 5.000 
movie name:  Made in Dagenham (2010)  pred rating: 8.611   mean rating: 2.000 
movie name:  The Wait (2015)  pred rating: 8.578   mean rating: 3.500 
movie name:  Legend of 1900, The (a.k.a. The Legend of the Pianist on the Ocean) (Leggenda del pianista sull'oceano) (1998)  pred rating: 8.554   mean rating: 3.667 


<h3>end</h3>