In [1]:
import numpy as np
import pylab as pl
import pandas as pd
import kMeans
from sklearn.cluster import KMeans
from decimal import *

<h4>Problem2(a)</h4>

In [2]:
getcontext().prec=6

In [3]:
def distCosine(a, b):
    """Takes 2 vectors a, b and returns the cosine similarity according 
    to the definition of the dot product
    """
    dot_product = np.dot(a, b)
    norm_a = np.linalg.norm(a)
    norm_b = np.linalg.norm(b)
    res=1
    if norm_a!=0 and norm_b!=0:
        res = np.divide(dot_product,(norm_a * norm_b))
    return res

<h4>Problem(b)</h4>

In [6]:
TD=pd.read_csv("E:/MyCourses/CSC478ProgrammingMachineLearning/homework3/newsgroups5/matrix.txt", sep=',',header = None)
DT=TD.T
DT

0     1     2     3     4     5     6     7     8     9     ...  9318  \
0        0     0     0     0     0     0     0     0     0     0  ...     0   
1        0     0     0     0     0     0     0     0     0     1  ...     0   
2        0     0     0     0     0     0     0     0     0     0  ...     0   
3        0     0     0     0     0     0     0     0     0     0  ...     0   
4        0     0     0     0     0     0     0     0     0     0  ...     0   
...    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
2495     0     0     0     0     0     0     0     0     0     0  ...     0   
2496     0     0     0     0     0     0     0     0     0     0  ...     0   
2497     0     0     0     0     0     0     0     0     0     0  ...     0   
2498     0     0     0     0     0     0     0     0     0     0  ...     0   
2499     0     0     0     0     0     0     0     0     0     0  ...     0   

      9319  9320  9321  9322  9323  9324  9325  9326  9327  
0        0     0     0     0     0     0     0     0     0  
1        0     0     0     0     0     0     0     0     0  
2        0     0     0     0     0     0     0     0     0  
3        0     0     0     0     0     0     0     0     0  
4        0     0     0     0     0     0     0     0     0  
...    ...   ...   ...   ...   ...   ...   ...   ...   ...  
2495     0     0     0     0     0     0     0     0     0  
2496     0     0     0     0     0     0     0     0     0  
2497     0     0     0     0     0     0     0     0     0  
2498     0     0     0     0     0     0     0     0     0  
2499     0     0     0     0     0     0     0     0     0  

[2500 rows x 9328 columns]

<h4>Transform the data to TFxIDF weights (not a must for clustering)</h4>

In [7]:
# Note: doc frequency (df) for a term t is the number of docs in which t appears divided by total number of docs

# first let's find the doc counts for each term

DF = pd.DataFrame([(TD!=0).sum(1)]).T
DF

0
0     10
1      6
2     22
3      9
4     13
...   ..
9323   6
9324   5
9325   3
9326   3
9327   4

[9328 rows x 1 columns]

In [8]:
numTerms=TD.shape[0]
NDocs = TD.shape[1]

In [9]:
# Create a matrix with all entries = NDocs
NMatrix=np.ones(np.shape(TD), dtype=float)*NDocs
np.set_printoptions(precision=2,suppress=True,linewidth=120)
print(NMatrix)

[[2500. 2500. 2500. ... 2500. 2500. 2500.]
 [2500. 2500. 2500. ... 2500. 2500. 2500.]
 [2500. 2500. 2500. ... 2500. 2500. 2500.]
 ...
 [2500. 2500. 2500. ... 2500. 2500. 2500.]
 [2500. 2500. 2500. ... 2500. 2500. 2500.]
 [2500. 2500. 2500. ... 2500. 2500. 2500.]]


In [10]:
IDF = np.log2(np.divide(NMatrix, np.array(DF)))
print(IDF)

[[7.97 7.97 7.97 ... 7.97 7.97 7.97]
 [8.7  8.7  8.7  ... 8.7  8.7  8.7 ]
 [6.83 6.83 6.83 ... 6.83 6.83 6.83]
 ...
 [9.7  9.7  9.7  ... 9.7  9.7  9.7 ]
 [9.7  9.7  9.7  ... 9.7  9.7  9.7 ]
 [9.29 9.29 9.29 ... 9.29 9.29 9.29]]


In [11]:
# Note: doc frequency (df) for a term t is the number of docs in which t appears divided by total number of docs

# first let's find the doc counts for each term

DF = pd.DataFrame([(TD!=0).sum(1)]).T
DF

0
0     10
1      6
2     22
3      9
4     13
...   ..
9323   6
9324   5
9325   3
9326   3
9327   4

[9328 rows x 1 columns]

In [12]:
# Finally compute the TFxIDF values for each document-term entry
TD_tfidf = TD * IDF
pd.set_option("display.precision", 2)
DT_tfidf = TD_tfidf.T
DT_tfidf

0     1     2     3     4     5     6     7     8     9     ...  9318  \
0      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  0.00  ...   0.0   
1      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  3.86  ...   0.0   
2      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  0.00  ...   0.0   
3      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  0.00  ...   0.0   
4      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  0.00  ...   0.0   
...    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
2495   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  0.00  ...   0.0   
2496   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  0.00  ...   0.0   
2497   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  0.00  ...   0.0   
2498   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  0.00  ...   0.0   
2499   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  0.00  ...   0.0   

      9319  9320  9321  9322  9323  9324  9325  9326  9327  
0      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
1      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
2      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
3      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
4      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
...    ...   ...   ...   ...   ...   ...   ...   ...   ...  
2495   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
2496   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
2497   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
2498   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
2499   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  

[2500 rows x 9328 columns]

In [13]:
y=pd.read_csv("E:/MyCourses/CSC478ProgrammingMachineLearning/homework3/newsgroups5/classes.txt",skiprows=1, sep=' ',header=None, index_col=0)
y

1
0      
0     0
1     1
2     1
3     1
4     2
...  ..
2495  4
2496  4
2497  3
2498  4
2499  2

[2500 rows x 1 columns]

In [52]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(DT_tfidf, y, test_size=.2, random_state=33)

<h4>Problem(c)</h4>

In [16]:
centroids_tfidf, clusters_tfidf = kMeans.kMeans(np.array(X_train), 5,distCosine)

begin calculation using <function distCosine at 0x00000206C5062E58>
Done!


In [54]:
X_train

0     1     2     3     4     5     6     7     8     9     ...  9318  \
1289   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
596    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
1935   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
2436   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
2349   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
...    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
2243   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
57     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
578    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
1752   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
2439   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   

      9319  9320  9321  9322  9323  9324  9325  9326  9327  
1289   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
596    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
1935   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
2436   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
2349   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
...    ...   ...   ...   ...   ...   ...   ...   ...   ...  
2243   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
57     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
578    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
1752   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
2439   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  

[2000 rows x 9328 columns]

In [114]:
centroids_tfidf

array([[  0.  ,   0.  ,   0.  , ...,   1.62,   0.  ,   0.  ],
       [  3.18,   0.46, 300.15, ...,   1.71,   4.96,   8.29],
       [  0.  ,   0.  ,   0.  , ...,   0.  ,   0.  ,   0.  ],
       [  0.02,   0.02,   0.25, ...,   0.01,   0.  ,   0.01],
       [  2.66,   0.  ,   0.  , ...,   0.  ,   0.  ,  12.38]])

In [113]:
X_train_result=X_train
#X_train_result.assign(label = clusters_tfidf[:,0])
#X_train_result.append(centroids_tfidf[0])
X_train_result.sort_values(by=['label'])

0    1    2    3      4    5    6    7    8    9  ...   9319  9320  \
1990  0.00  0.0  0.0  0.0   0.00  0.0  0.0  0.0  0.0  0.0  ...   0.00   0.0   
1555  0.00  0.0  0.0  0.0   0.00  0.0  0.0  0.0  0.0  0.0  ...   0.00   0.0   
2044  0.00  0.0  0.0  0.0   0.00  0.0  0.0  0.0  0.0  0.0  ...   0.00   0.0   
1392  0.00  0.0  0.0  0.0   7.59  0.0  0.0  0.0  0.0  0.0  ...   8.97   0.0   
1794  0.00  0.0  0.0  0.0   0.00  0.0  0.0  0.0  0.0  0.0  ...   0.00   0.0   
...    ...  ...  ...  ...    ...  ...  ...  ...  ...  ...  ...    ...   ...   
1821  0.00  0.0  0.0  0.0   0.00  0.0  0.0  0.0  0.0  0.0  ...   0.00   0.0   
1253  0.00  0.0  0.0  0.0   0.00  0.0  0.0  0.0  0.0  0.0  ...   0.00   0.0   
2413  7.97  0.0  0.0  0.0  22.76  0.0  0.0  0.0  0.0  0.0  ...  53.79   0.0   
2448  0.00  0.0  0.0  0.0   0.00  0.0  0.0  0.0  0.0  0.0  ...   0.00   0.0   
1537  0.00  0.0  0.0  0.0   0.00  0.0  0.0  0.0  0.0  0.0  ...   0.00   0.0   

       9321   9322  9323  9324  9325  9326   9327  label  
1990   0.00   0.00   0.0   0.0   0.0   0.0   0.00    0.0  
1555   0.00   0.00   0.0   0.0   9.7   0.0   0.00    0.0  
2044   0.00   0.00   0.0   0.0   0.0   0.0   0.00    0.0  
1392  69.62   0.00   0.0   0.0   0.0   0.0   0.00    0.0  
1794  34.81   0.00   0.0   0.0   0.0   0.0   0.00    0.0  
...     ...    ...   ...   ...   ...   ...    ...    ...  
1821   0.00   0.00   0.0   0.0   0.0   0.0   0.00    3.0  
1253   0.00   0.00   0.0   0.0   0.0   0.0   0.00    3.0  
2413   0.00  29.11   0.0   0.0   0.0   0.0  37.15    4.0  
2448   0.00   0.00   0.0   0.0   0.0   0.0   0.00    4.0  
1537   8.70   0.00   0.0   0.0   0.0   0.0   0.00    4.0  

[2000 rows x 9329 columns]

In [73]:
X_train_result.groupby(['label']).size()

label
0.0       6
2.0       2
3.0    1989
4.0       3
dtype: int64

In [125]:
g=X_train_result.groupby('label')
#g.groups.keys()
#group0=X_train_result[X_train_result.label == 0]
#group0.describe()
#g.max() 
#g.mean() 
total_by_group=g.sum()
total_by_group

0      1       2      3       4      5       6      7       8     \
label                                                                      
0.0     0.00   0.00    0.00   0.00    7.59   0.00    0.00   0.00    0.00   
2.0     0.00   0.00    0.00   0.00    0.00   0.00    0.00   0.00    0.00   
3.0    47.79  34.81  498.46  64.94  106.22  81.18  280.76  19.41  323.34   
4.0     7.97   0.00    0.00   0.00   22.76   0.00    0.00   0.00    0.00   

        9     ...   9318   9319   9320    9321   9322   9323    9324   9325  \
label         ...                                                             
0.0      0.0  ...   0.00   8.97   0.00  104.43   0.00   0.00    0.00   9.70   
2.0      0.0  ...   0.00   0.00   0.00    0.00   0.00   0.00    0.00   0.00   
3.0    691.2  ...  59.36   8.97  29.11   17.41   9.70  69.62  286.91  19.41   
4.0      0.0  ...  16.96  53.79   0.00    8.70  29.11   0.00    0.00   0.00   

       9326   9327  
label               
0.0     0.0   0.00  
2.0     0.0   0.00  
3.0     9.7  18.58  
4.0     0.0  37.15  

[4 rows x 9328 columns]

In [60]:
clusters_tfidf[:,0]

array([3., 3., 3., ..., 3., 3., 3.])

<h4>problem2(d)</h4>

In [19]:
y_train_arr=np.array(y_train).flatten()
y_train_arr

array([4, 0, 4, ..., 2, 0, 1], dtype=int64)

In [20]:
def cluster_sizes(clusters):
    #clusters is an array of cluster labels for each instance in the data
    size = {}
    cluster_labels = np.unique(clusters)
    n_clusters = cluster_labels.shape[0]
    for c in cluster_labels:
        size[c] = len(clusters[clusters == c])
    return size

In [21]:
size=cluster_sizes(y_train_arr)
size

{0: 410, 1: 406, 2: 392, 3: 402, 4: 390}

In [22]:
size=cluster_sizes(clusters_tfidf[:,0])
size

{0.0: 6, 2.0: 2, 3.0: 1989, 4.0: 3}

In [23]:
from sklearn.metrics import completeness_score, homogeneity_score

In [24]:
target=y_train_arr
c=clusters_tfidf[:,0]
print(completeness_score(target,c))
print(homogeneity_score(target,c))

0.1802710051707117
0.0044330953009153965


In [34]:
clusters_tfidf

array([[3., 0.],
       [3., 0.],
       [3., 0.],
       ...,
       [3., 0.],
       [3., 0.],
       [3., 0.]])

<h4>Problem2(e)</h4>

In [25]:
centroids_tfidf

array([[  0.  ,   0.  ,   0.  , ...,   1.62,   0.  ,   0.  ],
       [  3.18,   0.46, 300.15, ...,   1.71,   4.96,   8.29],
       [  0.  ,   0.  ,   0.  , ...,   0.  ,   0.  ,   0.  ],
       [  0.02,   0.02,   0.25, ...,   0.01,   0.  ,   0.01],
       [  2.66,   0.  ,   0.  , ...,   0.  ,   0.  ,  12.38]])

In [26]:
X_test

0     1     2     3     4     5     6      7     8     9     ...  9318  \
1590   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.00   0.0   0.0  ...   0.0   
277    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.00   0.0   0.0  ...   0.0   
2297   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.00   0.0   0.0  ...   0.0   
1739   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.00   0.0   0.0  ...   0.0   
511    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.00   0.0   0.0  ...   0.0   
...    ...   ...   ...   ...   ...   ...   ...    ...   ...   ...  ...   ...   
1637   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.00   0.0   0.0  ...   0.0   
1092   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.00   0.0   0.0  ...   0.0   
559    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.00   0.0   0.0  ...   0.0   
1918   0.0   0.0   0.0   0.0   0.0   0.0   0.0  19.41   0.0   0.0  ...   0.0   
929    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.00   0.0   0.0  ...   0.0   

      9319  9320  9321  9322  9323  9324  9325  9326  9327  
1590   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
277    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
2297   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
1739   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
511    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
...    ...   ...   ...   ...   ...   ...   ...   ...   ...  
1637   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
1092   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
559    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
1918   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
929    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  

[500 rows x 9328 columns]

In [27]:
def predict(arr, centroid):
    x=len(arr)
    y=len(centroid)
    list=[]
    for i in range(x):
        temp=float('inf')
        p=0
        for j in range(y):
            cur=distCosine(arr[i],centroid[j])
            if(temp>cur):
                temp=cur
                p=j
        list.append((p,temp)) 
    return np.array(list)

In [28]:
cluster=predict(np.array(X_test),centroids_tfidf)
cluster

array([[2.  , 0.  ],
       [0.  , 0.  ],
       [0.  , 0.  ],
       [0.  , 0.  ],
       [0.  , 0.  ],
       [0.  , 0.  ],
       [0.  , 0.  ],
       [0.  , 0.  ],
       [0.  , 0.  ],
       [0.  , 0.  ],
       [0.  , 0.  ],
       [0.  , 0.  ],
       [2.  , 0.  ],
       [2.  , 0.  ],
       [0.  , 0.  ],
       [0.  , 0.  ],
       [0.  , 0.  ],
       [0.  , 0.  ],
       [0.  , 0.  ],
       [0.  , 0.  ],
       [0.  , 0.  ],
       [0.  , 0.  ],
       [0.  , 0.  ],
       [0.  , 0.  ],
       [0.  , 0.  ],
       [0.  , 0.  ],
       [0.  , 0.  ],
       [0.  , 0.  ],
       [0.  , 0.  ],
       [0.  , 0.  ],
       [0.  , 0.  ],
       [0.  , 0.  ],
       [0.  , 0.  ],
       [0.  , 0.  ],
       [0.  , 0.  ],
       [0.  , 0.  ],
       [2.  , 0.  ],
       [0.  , 0.  ],
       [0.  , 0.  ],
       [0.  , 0.  ],
       [0.  , 0.  ],
       [0.  , 0.  ],
       [0.  , 0.  ],
       [2.  , 0.  ],
       [0.  , 0.  ],
       [0.  , 0.  ],
       [0.  , 0.  ],
       [0.  ,

In [29]:
cluster_sizes(cluster[:,0])

{0.0: 446, 2.0: 51, 3.0: 1, 4.0: 2}